### PR TITLE
Skip certificate validation

### PR DESCRIPTION
**Pull request by Mac351**
This PR enables a parameter to skip certificate SSL validation. It's useful if you're using a self signed certificate or an invalid one, but still need to use SSL/TLS.

For my purposes, I'm using an NGINX pass through proxy when sending data to AWS IoT, so the aws certificate doesn't match. In production I'll be using DNS rewrite, so the certificates will match. But for the purposes of load testing the NGINX proxy, I want to skip certificate validation.

### CODE REVIEW

**Comment by hikhvar** [comment]
Could you please rebased your brach on the master branch? At the moment, you merged inovex/master into your brach.

**Comment by Mac351** [comment]
I'm sorry, but I'm not sure what you mean. Are you able to explain what you mean by "rebased your brach on the master branch"?

**Comment by hikhvar** [comment]
This pull request contains the commit 0aedb45. This is a merge commit we want to avoid in the history of the project. From the text of the commit I assume that you named this upstream remote `inovex` in I think the following commands should do the trick:
```
git fetch inovex
git rebase -i inovex/master
git push
```
I think you need to push with the `-f` paramter. Since the `-f` is potential disruptive, please check if everything is correct. Peronally I use `gitg --all` or `gitk --all` to check the branches and commits localy before pushing.

**Comment by hikhvar** [comment]
Close this PR since the flag `"skip-tls-verification"` already implements this behavior.

**Pull request closed without merging**
